apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.config.name }}
  labels:
    group: {{ .Values.postgres.group }}
data: 
{{- range .Values.postgres.config.data }}
  {{ .key }}: {{ .value }}
{{- end}}
  